### ISSUE TITLE
Saved extension in grant for endpoint authorize cleared in token endpoint

### ISSUE THREAD

**Issue by thomaskrause** [HeroicKatora/oxide-auth#126]
# Bug report

I add some extensions to the grant by using extensions and the information of the request in the authorize endpoint.
For authorizing, the default `AuthMap` with the internal `token` hash map is used.
Thi causes unexpected behaviour (or maybe I don't read the documentation) right

The effects of this bug are &#8230;

## Reproduction

Relevant environment (http frontend library, OS, network setup?)

1. Create a sample application with the default authorizer
2. Add an extension in the authorize endpoint
3. Try to read the extension in the token endpoint

From what I see the information is lost in the following line

https://github.com/HeroicKatora/oxide-auth/blob/216d461c8c8c1b8c6b679fe0ecb40d0b9d9fc842/oxide-auth/src/code_grant/accesstoken.rs#L290

The `Input::Extended { access_extensions }` has already been cleared before by a `mem::take` in https://github.com/HeroicKatora/oxide-auth/blob/216d461c8c8c1b8c6b679fe0ecb40d0b9d9fc842/oxide-auth/src/code_grant/accesstoken.rs#L395

and the `extensions` field of the `Extend` variant, to which this is replaced into, is ignored when creating the new access token.

## Expected behaviour

I do think the intention was to return the pre-created grant with all the extensions.

Tracking pull request
--------

 - [ ] A pull request does not yet exist/

**Comment by HeroicKatora** [comment]
Right, although my fault analysis differs a bit. The root is (somewhat) bad naming. Note that based on the code (and whatever I can remember from my initial thoughts) `Extension::extend` is supposed to _modify_ the second parameter and return the complete result dictionary. Hence why the extension attribute is ignored on the state. The removal in line 395 shouldn't have anything to do with this, however, because the `extensions` variable is immediately added back into the new state and then assigned to `self.state` as a result of that line:

https://github.com/HeroicKatora/oxide-auth/blob/216d461c8c8c1b8c6b679fe0ecb40d0b9d9fc842/oxide-auth/src/code_grant/accesstoken.rs#L289

The problem is that not even the default extension, `()`, adheres to the expectation of returning existing values but rather ignores them and returns an empty set:

https://github.com/HeroicKatora/oxide-auth/blob/216d461c8c8c1b8c6b679fe0ecb40d0b9d9fc842/oxide-auth/src/code_grant/accesstoken.rs#L94-L98

**Comment by HeroicKatora** [comment]
¹I preferred modifying the set to avoid accidentally duplicating a one-time-token or something of that sort.

**Comment by thomaskrause** [comment]
Ah, thank you very much for this hint! I moved all my actual logic to create extensions to an implementation of `AuthorizationExtension`. For the token endpoint I just a simple extension that copies the existing data.

```rust
struct CopyExtension {}

impl Extension for CopyExtension {
    fn access_token(&mut self) -> Option<&mut dyn AccessTokenExtension> {
        Some(self)
    }
}

impl AccessTokenExtension for CopyExtension {
    fn extend(
        &mut self,
        _request: &dyn oxide_auth::code_grant::accesstoken::Request,
        data: oxide_auth::primitives::grant::Extensions,
    ) -> std::result::Result<oxide_auth::primitives::grant::Extensions, ()> {
        Ok(data)
    }
}
```
