### ISSUE TITLE
Usage of this library not clearly stated in docs.

### ISSUE THREAD

**Issue by trsh** [HeroicKatora/oxide-auth#19]
Project Improvement
======

I dot not understand from docs if can can Plug-in this into an existing project. Sorry, maybe it's my brain not working today.

**Comment by HeroicKatora** [comment]
Ideally, this should be a guide section in the documentation. Meanwhile:

There are three possible use cases:
- Use one of the `frontends` to run an OAuth access point within a web framework,
- Adapt your own web library as a frontend (for this the guide already exists, in [`frontends`](https://docs.rs/oxide-auth/0.3.1/oxide_auth/frontends/index.html).
- Extends one of the [`primitives`](https://docs.rs/oxide-auth/0.3.1/oxide_auth/primitives/index.html) or [`extensions`](https://docs.rs/oxide-auth/0.3.1/oxide_auth/primitives/index.html) to hook inside the OAuth process. For example, it might be necessary to persist the tokens to a database instead of the provided methods.

**Comment by HeroicKatora** [comment]
Included in the top-level library documentation since 169ef0053ef744ec67622fefc790e098505cf752 (v0.4.0-preview.0)
