### ISSUE TITLE
Include mention of iron deprecation somewhere

### ISSUE THREAD

**Issue by toulouse** [HeroicKatora/oxide-auth#23]
Project Improvement
======

I'm picking up iron as a framework since I want something lighterweight than actix or rocket, and found this crate when looking to implement OAuth2. There is an example for iron in the examples/ directory, but it is broken and uses a module which is no longer exported from the frontends module, though the source file remains. Looking into the commits there's no explicit deprecation, it just seems like it got lost in a refactoring, but it appears it was likely intentional, as a previous revision of Migration.md mentioned it was deprecated. It would be nice to provide guidance to iron users - if the iron frontend shouldn't be available then the example could perhaps incorporate a supported way to integrate with iron.

Tracking pull request
--------

 - [ ] A pull request does not yet exist

**Comment by toulouse** [comment]
Note: I see this as slight separate from issue 14 as it deals with the fact that there's misleading dead code which ought to be removed (if the deprecation is true) or reenabled (if not). Documentation is adjacent but not exactly the same issue.

**Comment by HeroicKatora** [comment]
Iron had been deprecated last year by its maintainer, but was partially reviewed now again. Also see [this commit from July that removes that warning](https://github.com/iron/iron/commit/7c9ff1ce7684ed7c2388733e8074d6cbe4348530).

Since this appears to no longer be the case, I'd like to bring it back when the first updated release is done, which appear to also want to enable a `future`-based approach. However in its current state there is a fair amount of legacy dependencies. What I want to avoid is refactoring the frontend integration now, just to then do it again when that large release of `iron` is published. I'll remove the code from 'master' in the meantime.

> I'm picking up iron as a framework since I want something lighterweight than actix or rocket, and found this crate when looking to implement OAuth2. 

Maybe you could use [`rouille`](https://docs.rs/rouille/3.0.0/rouille/) for a new simple and lightweight project. That is not a migration path of course but the deprecation warning was there for mostly that reason. I'm sorry for the trouble cause by this.

**Comment by HeroicKatora** [comment]
The fact that this was implemented in 3 hours with a fully working example, I think is a fairly convincing indication that the frontend interface is in fact quite reasonable now.

**Comment by HeroicKatora** [comment]
Thanks for nagging me to do it anyways ;)
